### ISSUE TITLE
Which hardware camera to use, pinout of board camera port

### ISSUE THREAD

**Issue by charkster** [MaximIntegratedAI/MAX78000_SDK#25]
In the MAX78000_SDK/Examples/MAX78000/CameraIF/main.c file it mentions the "Parallel camera example with the OV7692".
Are there any commercial camera boards that can interface to the development board?
Thanks.

**Comment by vicloginov** [comment]
The MAX78000 Evaluation Kit is supplied with OV7692 camera module. This module is connected to Evaluation Kit with 24 pin header. The pinout information you can find here:
https://datasheets.maximintegrated.com/en/ds/MAX78000EVKIT.pdf
The MAX78000 Feather has OV7692 camera populated on board.

**Comment by vicloginov** [comment]
You can find MAX78000 Feather datasheet here:
https://datasheets.maximintegrated.com/en/ds/MAX78000FTHR.pdf
