### ISSUE TITLE
MAX78000FTHR TFT example seems to use same CS pin for Display and SRAM chip

### ISSUE THREAD

**Issue by lab-mathias-claussen** [MaximIntegratedAI/MAX78000_SDK#29]
MAX78000FTHR TFT example seems to use same CS pin for Display and SRAM chip. Wont there be any harm to the QSPI Ram onbaord if the display is used like discribed on Github?

Best Regards

**Comment by vicloginov** [comment]
The SRAM_CS and TFT_CS signals are connected to different MAX78000 pins. SRAM_CS= P0.10/QSPI0_SS2 and TFT_CS=P0.11/QSPI0_SS1
