### ISSUE TITLE
Driver for MAX9867 is missing in SDK

### ISSUE THREAD

**Issue by lab-mathias-claussen** [MaximIntegratedAI/MAX78000_SDK#30]
For the used MAX9867 there is no dirver within the SDK supplied. 
Will there be a seperate BSP that will include this driver?
Description how to handle I²S Mic and Codec on same I²S interface also missing

**Comment by jessexm** [comment]
A driver for the MAX9867 will be supplied with an upcoming example. 
Use of the I²S Mic and I²S Codec are mutually exclusive; power to the microphone is controlled by the MAX20303 PMIC.
