### ISSUE TITLE
sdhc.h and sdhc.c is missing 

### ISSUE THREAD

**Issue by Birdack** [MaximIntegratedAI/MAX78000_SDK#33]
Is included SDHC library and FF13 (fat32 lib) but there is no sdhc.c and sdhc.h board specific peripheral library.

`  CC    Source/sdhc_lib.c
Source/sdhc_lib.c:47:10: fatal error: sdhc.h: No such file or directory
   47 | #include "sdhc.h"
      |          ^~~~~~~~`

**Comment by vicloginov** [comment]
We are aware of the issue. The driver requires update to work on MAX78000 Feather. It will be added to future SDK releases.

**Comment by rotx-maxim** [comment]
This should be addressed in #37
