### ISSUE TITLE
SD card over SPI clock

### ISSUE THREAD

**Issue by MRotaKalpa** [MaximIntegratedAI/MAX78000_SDK#39]
I was testing the new SDCard support and I was wondering what's the reasoning behind the default SPI clock of 400Khz set [here](https://github.com/MaximIntegratedAI/MAX78000_SDK/blob/de233e17abea86f94a05444cf59f43b2d2c12352/Libraries/SDHC/ff13/Source/diskio.c#L366).
Theoretically this could be pushed up to 50Mhz, am I correct? Or there are some other limits that I am not aware of?

**Comment by jessexm** [comment]
The SPI clock speed can be increased after the initial transactions placing the SD Card into SPI mode.  A future release will include the SPI clock speedup.
