### ISSUE TITLE
CNN hangs after entering LPM (or below)

### ISSUE THREAD

**Issue by MRotaKalpa** [MaximIntegratedAI/MAX78000_SDK#40]
I was trying to integrate a CNN example with a WUT (with SLEEP / LPM) using the following examples:
- [CNN mnist](https://github.com/MaximIntegratedAI/MAX78000_SDK/tree/master/Examples/MAX78000/CNN/mnist)
- [WUT](https://github.com/MaximIntegratedAI/MAX78000_SDK/tree/master/Examples/MAX78000/WUT)

Here's the [gist](https://gist.github.com/MRotaKalpa/b464ef61153b255a7196b5adc1191f38) with my code which is 95% the mnist one with just a infinite loop and the WUT / `MXC_EnterXMode()` routines.

SLEEP Mode does indeed work, the board enters this state, then wakes up and repeats the whole process without any problem.

On the other hand, with Low Power Mode (or any below for the matter) I'm experiencing some unforeseen consequences.
Here the board enters LPM, wakes up and upon repeating the CNN routine a second time, it hangs while [waiting for CNN interrupts](https://gist.github.com/MRotaKalpa/b464ef61153b255a7196b5adc1191f38#file-main-c-L133).
But this does **not** happen if I explicitly [wait some time](https://gist.github.com/MRotaKalpa/b464ef61153b255a7196b5adc1191f38#file-main-c-L129) after calling `cnn_start`.

**Comment by aniktash** [comment]
In LPM, CNN interrupt cannot wake up the ARM core. But WUT can. You can use SLEEP mode instead.

For more information on modes of operation and power optimization, please check: 
https://www.maximintegrated.com/en/design/technical-documents/app-notes/7/7417.html

**Comment by MRotaKalpa** [comment]
But that's not what I'm trying to accomplish.
WUT **is** waking up the ARM core from LPM (see [line 154](https://gist.github.com/MRotaKalpa/b464ef61153b255a7196b5adc1191f38#file-main-c-L154)), but after that it appears that I have to wait some time (see [line 129](https://gist.github.com/MRotaKalpa/b464ef61153b255a7196b5adc1191f38#file-main-c-L129)) before calling `__WFI` if I do not want the device to hang forever.

This should be also similar to the `faceid_evkit` [example](https://github.com/MaximIntegratedAI/MAX78000_SDK/blob/59fdffad53ab13b733d1bbf517f5f62bccbc0816/Examples/MAX78000/CNN/faceid_evkit/src/state_faceID.c#L137) where the device can be put in LPM and woke up via WUT (see [here](https://github.com/MaximIntegratedAI/MAX78000_SDK/blob/59fdffad53ab13b733d1bbf517f5f62bccbc0816/Examples/MAX78000/CNN/faceid_evkit/src/state_faceID.c#L203)) but probably here everything works since it also has to wait for the camera interrupts (thus leaving some time before the next CNN iteration).

**Comment by aniktash** [comment]
The added delay in line 129 makes it finish the CNN inference, so when you hit the while (cnn_time == 0), CNN_time is not zero.
The problem is the API MXC_LP_EnterLowPowerMode sets a flag (SCB->SCR |= SCB_SCR_SLEEPDEEP_Msk) which causes any __WFI() to be deep sleep, instead of sleep. CNN interrupts cannot wake up Arm from deep sleep (LPM). So your first run works, but the second run after MXC_LP_EnterLowPowerMode is called is going to stuck at __WFI.    You can replace __WFI() with MXC_LP_EnterSleepMode(),   or  clear deep sleep bit prior to calling __WFI (SCB->SCR &= ~SCB_SCR_SLEEPDEEP_Msk)

**Comment by MRotaKalpa** [comment]
That does work, thanks for the clarification!
