### ISSUE TITLE
Support for Sensors

### ISSUE THREAD

**Issue by ankur608** [MaximIntegratedAI/MAX78000_SDK#43]
Is there any support for external sensors (I2C) or libraries on MAX78000 platform.

**Comment by rotx-maxim** [comment]
The SDK has several examples that use I2C communication (for example, the camera on the EVkit uses I2C for configuration). Is there a particular sensor you need help with? If it is made by Maxim Integrated, we should be able to offer additional assistance.

**Comment by ankur608** [comment]
Generic I2C sensors like MAX30102 or accelerometer (ADXL345).

**Comment by jessexm** [comment]
See [I2C_ADXL343](https://github.com/MaximIntegratedAI/MAX78000_SDK/tree/master/Examples/MAX78000/I2C_ADXL343) for I2C accelerometer example.
