### ISSUE TITLE
undefined reference to `sensor_register` in faceid_evkit example

### ISSUE THREAD

**Issue by pradoz** [MaximIntegratedAI/MAX78000_SDK#51]
## Overview
Using the Eclipse Maxim SDK and cloning the recent version of the SDK+Examples, I am unable to build to [faceid_evkit example](https://github.com/MaximIntegratedAI/MAX78000_SDK/tree/master/Examples/MAX78000/CNN/faceid_evkit).

## Steps to reproduce
1. Have a working MAX78000 FTHR using the MNIST example
2. Change references to the EvKit board to the FTHR board in `Makefile`, i.e.
```C
ifeq "$(BOARD)" ""
  #BOARD=EvKit_V1
  BOARD=FTHR_RevA
endif
```
3. Run `make clean`
4. Build the project

## Error logs
```
08:53:45 **** Incremental Build of configuration Default for project faceid_evkit ****
make all 
  CC    ../../../../Libraries/Boards/MAX78000/EvKit_V1/../Source/camera.c
  LD    /c/Users/pradoz/Desktop/MAX78000_SDK/Examples/MAX78000/CNN/faceid_evkit/build/faceid_evkit.elf 
c:/maximsdk/tools/gnutools/bin/../lib/gcc/arm-none-eabi/9.2.1/../../../../arm-none-eabi/bin/ld.exe: c:/Users/pradoz/Desktop/MAX78000_SDK/Examples/MAX78000/CNN/faceid_evkit/build/camera.o: in function `camera_init':
C:\Users\pradoz\Desktop\MAX78000_SDK\Examples\MAX78000\CNN\faceid_evkit/../../../../Libraries/Boards/MAX78000/EvKit_V1/../Source/camera.c:293: undefined reference to `sensor_register'
collect2.exe: error: ld returned 1 exit status
make: *** [/c/Users/pradoz/Desktop/MAX78000_SDK/Examples/MAX78000/CNN/faceid_evkit/build/faceid_evkit.elf] Error 1
"make all" terminated with exit code 2. Build might be incomplete.
```

**Comment by Jake-Carter** [comment]
Thank you for the detailed report.  

Please find a fixed project attached.  There were some issues with this project's Makefile that we're working on integrating into the next release.

[faceid_evkit-fixed.zip](https://github.com/MaximIntegratedAI/MAX78000_SDK/files/7621495/faceid_evkit-fixed.zip)

**Comment by Jake-Carter** [comment]
This issue is now resolved in the latest release of the SDK (see [PR#52](https://github.com/MaximIntegratedAI/MAX78000_SDK/pull/52) and [release notes](https://github.com/MaximIntegratedAI/MAX78000_SDK/blob/master/README.md)).  

Please pull from this repo or update via the [installer](https://www.maximintegrated.com/en/design/software-description.html/swpart=SFW0010820A).
