### ISSUE TITLE
I2C 10-bit addresses for master and slave configurations, are they supported?

### ISSUE THREAD

**Issue by marcosgatcomputer** [MaximIntegratedAI/MAX78000_SDK#53]
Hello,

A nice and shiny MAX78000 feather board just came into my hands very recently and I wanted to get busy with an old project consisting of a simple I2C scanner with support for 10-bit addresses.

According to section 14.2 the [MAX78000 manual](https://pdfserv.maximintegrated.com/en/an/ug7456.pdf) both 7 and 10-bit addresses are supported (the section's title is _I2C Master/Slave Features_ so I was guessing it would be straight-forward to use this micro for my project).

Further down the line, I'm now reviewing the code and I'm thinking **10-bit addressing is only supported for slaves**, maybe somebody can comment.

In my (very limited) understanding, when defining a device as master and starting a transaction (line [692](https://github.com/MaximIntegratedAI/MAX78000_SDK/blob/3a575e212e4877f8d34d5cfec2a3701af3a5400b/Libraries/PeriphDrivers/Source/I2C/i2c_reva.c#L698) of file ./MAX78000_SDK/Libraries/PeriphDrivers/Source/I2C/i2c_reva.c):

```c
int MXC_I2C_RevA_MasterTransaction (mxc_i2c_reva_req_t* req)
{
    mxc_i2c_reva_regs_t* i2c = req->i2c; // Save off pointer for faster access
    unsigned int written = 0;
    unsigned int read = 0;
    
    if (req->addr > MXC_I2C_REVA_MAX_ADDR_WIDTH) {
        return E_NOT_SUPPORTED;
    }
```

The offending part is the last conditional; looking into the header file (line [51](https://github.com/MaximIntegratedAI/MAX78000_SDK/blob/3a575e212e4877f8d34d5cfec2a3701af3a5400b/Libraries/PeriphDrivers/Source/I2C/i2c_reva.h#L51) MXC_I2C_REVA_MAX_ADDR_WIDTH is `0x7F` so 10-bit addresses are indeed not supported.

A little further down (line [106](https://github.com/MaximIntegratedAI/MAX78000_SDK/blob/3a575e212e4877f8d34d5cfec2a3701af3a5400b/Libraries/PeriphDrivers/Source/I2C/i2c_reva.c#L106)) where the slave address is defined we find these:

```c
 if (slaveAddr > MXC_I2C_REVA_MAX_ADDR_WIDTH) {
        // Set for 10bit addressing mode
        i2c->slave = MXC_F_I2C_REVA_SLAVE_EXT_ADDR_EN;
    }

```
Which seems to be a flag to activate 10-bit addressing.

I'm guessing it should not be a huge effort to add support for the master to work with 10-bit addresses but **I would like to know if this feature is planned for the near future** or maybe there are problems I'm not able to see before looking at the low-level.

For other MCs I've seen libraries that lack support for 10-bit addresses altogether but this is the first time I find partial support only, I'm wondering what's the reason...

Thank you for your efforts with these libraries and drivers.

**Comment by maximreza** [comment]
It is a driver limitations not hardware. Using 10-bit master should be as easy as setting the EX_ADDR_EN in the MSTCTRL register and then write two bytes of address to the TXFIFO. We will update the driver in our next release of SDK.

**Comment by marcosgatcomputer** [comment]
Great, that's what I thought. Thank you very much for your help.
