### ISSUE TITLE
how can i use the maxim_bitmap_converter.exe to convert imgs to all_imgs.c

### ISSUE THREAD

**Issue by ZhugeKongan** [MaximIntegratedAI/MAX78000_SDK#54]
https://github.com/MaximIntegratedAI/MAX78000_SDK/tree/master/Examples/MAX78000/CNN/faceid_evkit/TFT/evkit

**Comment by vicloginov** [comment]
This document describes how to use this utility: 
[AppNote-MaximBitmapConverterTool.pdf](https://github.com/MaximIntegratedAI/MAX78000_SDK/files/7803873/AppNote-MaximBitmapConverterTool.pdf)

**Comment by ZhugeKongan** [comment]
thanks
