### ISSUE TITLE
Unable to upload firmware due to GDB Error

### ISSUE THREAD

**Issue by drummerhul** [MaximIntegratedAI/MAX78000_SDK#57]
I can't upload firmware onto my MAX78000 EvKit or MAX78000 FTHR. I've tried uploading through the Maxim SDK on Windows 11 and a Windows 10 VM (both through Eclipse and minigw). Additionally, I've tried uploading through the CLI in 
Linux (Ubuntu 21.04). I'm getting the same error. 

Here's the message output of the command line:
``` bash
../openocd -f interface/cmsis-dap.cfg -f target/max78000.cfg  # from the Tools/OpenOCD/scripts directory
Open On-Chip Debugger 0.10.0+dev-g90939caf-dirty (2020-05-20-17:20)
Licensed under GNU GPL v2
For bug reports, read
	http://openocd.org/doc/doxygen/bugs.html
DEPRECATED! use 'adapter driver' not 'interface'
Info : Listening on port 6666 for tcl connections
Info : Listening on port 4444 for telnet connections
Info : CMSIS-DAP: SWD  Supported
Info : CMSIS-DAP: FW Version = 1.0
Info : CMSIS-DAP: Interface Initialised (SWD)
Info : SWCLK/TCK = 0 SWDIO/TMS = 1 TDI = 0 TDO = 0 nTRST = 0 nRESET = 0
Info : CMSIS-DAP: Interface ready
Info : clock speed 2000 kHz
Info : SWD DPIDR 0x2ba01477
Info : max32xxx.cpu: hardware has 6 breakpoints, 4 watchpoints
Info : starting gdb server for max32xxx.cpu on 3333
Info : Listening on port 3333 for gdb connections     # Hangs right here until the reset button on board is pressed
Polling target max32xxx.cpu failed, trying to reexamine  # Output after EvKit reset
Error: Could not find MEM-AP to control the core
Examination failed, GDB will be halted. Polling again in 100ms
Info : SWD DPIDR 0x2ba01477
Info : max32xxx.cpu: external reset detected
Polling target max32xxx.cpu failed, trying to reexamine
Info : max32xxx.cpu: hardware has 6 breakpoints, 4 watchpoints

```
I've had the EVKit and FTHR for a while, I bought them shortly after release. I was able to upload examples using previous versions of the SDK using the Maxim SDK on Windows through Eclipse and on Linux using both Eclipse and the CLI.

I would appreciate any additional troubleshooting guidance.

**Comment by Jake-Carter** [comment]
Hello, you're launching OpenOCD correctly but where you have marked `# Hangs right here until the reset button on board is pressed` is actually OpenOCD waiting for a GDB client connection.  The rest of your log file looks standard and what you would expect having reset the core while OpenOCD is connected.

Once OpenOCD reaches `Info : Listening on port 3333 for gdb connections`, you should then open a separate shell and connect to the OpenOCD server with your GDB client.  You may do so with the following commands:

1. `arm-none-eabi-gdb` (launches GDB client)
2. `target remote localhost:3333` (connects GDB client to the OpenOCD server running locally in the other shell)
3. `monitor reset halt` (now you can issue a reset over the SWD port)

GDB should have looked something like this:
```bash 
arm-none-eabi-gdb
GNU gdb (GNU Tools for Arm Embedded Processors 9-2019-q4-major) 8.3.0.20190709-git
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>     
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "--host=i686-w64-mingw32 --target=arm-none-eabi".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word".
(gdb) target remote localhost:3333
Remote debugging using localhost:3333
warning: No executable has been specified and target does not support
determining executable automatically.  Try using the "file" command.
0x10000884 in ?? ()
(gdb) monitor reset halt
SWD DPIDR 0x2ba01477
target halted due to debug-request, current mode: Thread
xPSR: 0x81000000 pc: 0x00002120 msp: 0x20003ff0
(gdb)
```

and your OpenOCD shell should look something like this:
```bash
Open On-Chip Debugger 0.10.0+dev-gdb3807dd7-dirty (2020-11-06-09:24)
Licensed under GNU GPL v2
For bug reports, read
        http://openocd.org/doc/doxygen/bugs.html
DEPRECATED! use 'adapter driver' not 'interface'
Info : Listening on port 6666 for tcl connections
Info : Listening on port 4444 for telnet connections
Info : CMSIS-DAP: SWD  Supported
Info : CMSIS-DAP: FW Version = 0256
Info : CMSIS-DAP: Serial# = 04441701ddccc19400000000000000000000000097969906
Info : CMSIS-DAP: Interface Initialised (SWD)
Info : SWCLK/TCK = 1 SWDIO/TMS = 1 TDI = 0 TDO = 0 nTRST = 0 nRESET = 1
Info : CMSIS-DAP: Interface ready
Info : clock speed 2000 kHz
Info : SWD DPIDR 0x2ba01477
Info : max32xxx.cpu: hardware has 6 breakpoints, 4 watchpoints
Info : max32xxx.cpu: external reset detected
Info : starting gdb server for max32xxx.cpu on 3333
Info : Listening on port 3333 for gdb connections
Info : accepting 'gdb' connection on tcp/3333
target halted due to debug-request, current mode: Thread
xPSR: 0x210e0000 pc: 0x10000884 msp: 0x2001ffe0
Info : SWD DPIDR 0x2ba01477
target halted due to debug-request, current mode: Thread
xPSR: 0x81000000 pc: 0x00002120 msp: 0x20003ff0
```

at this point the micro is reset and the program counter is halted.  From here, you can flash a program from the GDB shell with:
1. `file [path to program binary]`
2. `load`

... but if you can get to a reset on the command line then that's a good indicator that the toolchain and debugger are working.  

If you encountered any errors in the steps above please let me know.  If not, can you provide a more detailed error log from Eclipse?

**Comment by drummerhul** [comment]
@Jake-Carter I was able to get the firmware to load through the CLI in Ubuntu.  Thanks.  Clearly user error.  

Here's the error from the Maxim SDK on Windows 11.  

![image](https://user-images.githubusercontent.com/10715200/150482225-b4e7055b-0774-47a2-a057-f6b16c46fc69.png)

Here is the terminal output:
```bash
Open On-Chip Debugger 0.10.0+dev-gdb3807dd7-dirty (2020-11-06-09:24)
Licensed under GNU GPL v2
For bug reports, read
	http://openocd.org/doc/doxygen/bugs.html
DEPRECATED! use 'adapter driver' not 'interface'
Started by GNU MCU Eclipse
Info : Listening on port 6666 for tcl connections
Info : Listening on port 4444 for telnet connections
Info : CMSIS-DAP: SWD  Supported
Info : CMSIS-DAP: FW Version = 1.0
Info : CMSIS-DAP: Interface Initialised (SWD)
Info : SWCLK/TCK = 0 SWDIO/TMS = 1 TDI = 0 TDO = 0 nTRST = 0 nRESET = 0
Info : CMSIS-DAP: Interface ready
Info : clock speed 2000 kHz
Info : SWD DPIDR 0x2ba01477
Info : max32xxx.cpu: hardware has 6 breakpoints, 4 watchpoints
Info : starting gdb server for max32xxx.cpu on 3333
Error: couldn't bind gdb to socket on port 3333: No error
```
Do I need to start the gdb server separately in a minGW terminal or command prompt?  In the past I didn't not get this error, so I'm assuming Eclipse handled this.  I do see a driver problem for the Olimix USB OCD. See screen shot:

![image](https://user-images.githubusercontent.com/10715200/150482760-03781da8-d662-429b-b534-4f72ca820472.png)

I'll have to post the Windows 10 VM error later.

**Comment by Jake-Carter** [comment]
Hi @drummerhul,

When using Eclipse, you shouldn't need to start anything manually.  Eclipse handles everything on the back-end.

`Error: couldn't bind gdb to socket on port 3333: No error` is a strange one and not something I've seen before, but Windows 11 is also untouched ground for us at the moment.  We haven't tested the OpenOCD binaries thoroughly on it.  Are you running your VMs from a Windows 11 host?

A native install of Ubuntu 20.04 is my official recommendation especially if you want to train models, as its the only officially supported OS and the most well-documented route.  Alternatively, there is some support for WSL or native Windows via MSYS2.  See [this](https://github.com/MaximIntegratedAI/ai8x-synthesis/blob/develop/docs/Windows.md) section of the readme for more details and links to setup guides

**Comment by drummerhul** [comment]
@Jake-Carter I've got the CLI tool chain working in Ubuntu.  That should be sufficient. Thanks for the help.  Closing the issue.
