### ISSUE TITLE
Error: Error connecting DP: cannot read IDR

### ISSUE THREAD

**Issue by Doruk-Dilmen** [MaximIntegratedAI/MAX78000_SDK#64]
I connected the USB cable of MAX78000FTHR board to the host. 
The 'Select Project Configuration' dialog is configured as follows:
![Capture1](https://user-images.githubusercontent.com/91119666/158579165-c29d3e4e-01e5-4324-8978-aa00365c5f40.PNG)
The 'ImportProjects ' dialog is configured as follows:
![Capture2](https://user-images.githubusercontent.com/91119666/158579995-c8973a68-d3cc-4986-8d48-cd644f58ceb1.PNG)
Then I am configured as follows:
![Capture3](https://user-images.githubusercontent.com/91119666/158580520-c8ca2919-d125-4ad4-8d54-ddca4759dfb0.PNG)
![Capture4](https://user-images.githubusercontent.com/91119666/158580532-9e24dea1-b9f1-41b9-b9da-23c2c5aa7f39.PNG)
Then Build Finished. 0 errors, 0 warnings.
When, I run the code, I take this error. I tried https://github.com/MaximIntegratedAI/MaximAI_Documentation/blob/master/MAX78000_Feather/README.md#how-to-unlock-a-max78000-that-can-no-longer-be-programmed but it's not worked.

![Capture](https://user-images.githubusercontent.com/91119666/158571352-517b7377-7f5f-460d-99cc-89c55cd9c11d.PNG)

> Open On-Chip Debugger 0.11.0+dev-g4f85f7914 (2021-12-16-13:53)
Licensed under GNU GPL v2
For bug reports, read
	http://openocd.org/doc/doxygen/bugs.html
DEPRECATED! use 'adapter driver' not 'interface'
Started by GNU MCU Eclipse
Info : Listening on port 6666 for tcl connections
Info : Listening on port 4444 for telnet connections
Info : CMSIS-DAP: SWD  supported
Info : CMSIS-DAP: Atomic commands supported
Info : CMSIS-DAP: Test domain timer supported
Info : CMSIS-DAP: FW Version = 0256
Info : CMSIS-DAP: Serial# = 0444170160dac03200000000000000000000000097969906
Info : CMSIS-DAP: Interface Initialised (SWD)
Info : SWCLK/TCK = 1 SWDIO/TMS = 1 TDI = 0 TDO = 0 nTRST = 0 nRESET = 1
Info : CMSIS-DAP: Interface ready
Info : clock speed 2000 kHz
Error: Error connecting DP: cannot read IDR

**Comment by Jake-Carter** [comment]
Hello, I tested my FTHR board with the same configuration that you used above and was able to flash and debug without an issue.  `Error: Error connecting DP: cannot read IDR` is usually an indicator of some generic connection issue between OpenOCD and the micro core that will take some more troubleshooting.

Can you attach the "DETAILS.TXT" inside of the "DAPLINK" drive that will be presented when you plug in your board?  Ex:
![image](https://user-images.githubusercontent.com/38844790/158640809-15b3b7b7-920a-41ad-8aec-b1648e0e7ccd.png)

**Comment by Doruk-Dilmen** [comment]
I realized, when I run kw20_demo configured as follows, I take this error first time. Other than the above settings, I changed only this configurations in makefile:
![Capture6](https://user-images.githubusercontent.com/91119666/158748445-dd598e8b-8824-444e-8d29-18f8543384d6.PNG)
![Capture7](https://user-images.githubusercontent.com/91119666/158748460-bb902f09-e5d0-487a-a085-27d15ada13ee.PNG)
Then, I run the code and code is working well. But, after that I run just Hello_World example and I started getting the error and I getting always same error. It doesn't matter which example I'm running.
> Open On-Chip Debugger 0.11.0+dev-g4f85f7914 (2021-12-16-13:53)
Licensed under GNU GPL v2
For bug reports, read
	http://openocd.org/doc/doxygen/bugs.html
DEPRECATED! use 'adapter driver' not 'interface'
Started by GNU MCU Eclipse
Info : Listening on port 6666 for tcl connections
Info : Listening on port 4444 for telnet connections
Info : CMSIS-DAP: SWD  supported
Info : CMSIS-DAP: Atomic commands supported
Info : CMSIS-DAP: Test domain timer supported
Info : CMSIS-DAP: FW Version = 0256
Info : CMSIS-DAP: Serial# = 0444170160dac03200000000000000000000000097969906
Info : CMSIS-DAP: Interface Initialised (SWD)
Info : SWCLK/TCK = 1 SWDIO/TMS = 1 TDI = 0 TDO = 0 nTRST = 0 nRESET = 1
Info : CMSIS-DAP: Interface ready
Info : clock speed 2000 kHz
Error: Error connecting DP: cannot read IDR

"DETAILS.TXT" file:
![Capture5](https://user-images.githubusercontent.com/91119666/158747036-755f5072-2443-4aef-8c6f-4394185d3673.PNG)

**Comment by Jake-Carter** [comment]
Thanks @Doruk-Dilmen, everything looks to be OK with your debugger firmware.

I think you're encountering a common issue that I have seen in the past.  The kws20_demo project enters deep sleep mode by default via the `SLEEP_MODE` compiler definition.

![image](https://user-images.githubusercontent.com/38844790/158874565-fa48f852-c1d0-439f-bb32-43db62fad54e.png)

There are two limitations of the debugger port on the MAX78000 that make this a problem:
1. The debugger cannot connect while the micro core is in reset.
2. The debugger cannot connect while the micro core is in low power mode.  

We have a 2-second delay window at the beginning of the firmware in an attempt to work around this.
![image](https://user-images.githubusercontent.com/38844790/158877913-c307f810-88b0-48c5-b590-3c92dd5a1ad0.png)

The debugger issues a reset when you launch it, so it should be able to theoretically hit this window.  However, in practice we have seen that this is still not the case.

The current recommended workarounds are:
1. Press and release SW4 (reset) while you launch the debugger to manually hit the 2-second delay window.
2. If using SW4 still doesn't work, follow the [recovery procedure](https://github.com/MaximIntegratedAI/MaximAI_Documentation/tree/master/MAX78000_Feather#how-to-unlock-a-max78000-that-can-no-longer-be-programmed) to completely erase the flash and start fresh.  This recovery procedure should work even if the core is in low power mode, and I've tested this myself.
3. Change the `SLEEP_MODE` compiler definition to `0` to disable sleep mode in the kws20_demo before you re-flash it to the micro.

The `SLEEP_MODE` default value will be changed in the next release of the SDK, and I have requested improvements to our debugger hardware to address the core issues above.

Please let me know if you're able to use the workarounds, or if you encounter any further difficulties.

**Comment by Jake-Carter** [comment]
Hi @Doruk-Dilmen, I will go ahead and close out this issue, but if there is anything else I can assist with don't hesitate to let me know.

**Comment by Doruk-Dilmen** [comment]
Hi @Jake-Carter,

Thank you very much for your help. My problem is solved.
