### ISSUE TITLE
Multiple Command Recognition

### ISSUE THREAD

**Issue by Doruk-Dilmen** [MaximIntegratedAI/MAX78000_SDK#65]
Hello,

I am using your kws20_demo, it is working really good. But what I want to ask is can I use this model with two commands and maybe with some time delay between them. For example, UP command combined with STOP resulting as "UP STOP".

**Comment by aniktash** [comment]
Hi, you can still use the same model to detect words individually and add a state machine to keep track of the last two words and process accordingly. Generally, words are expected to be 1 sec each. But you may try to do some adjustments to shrink the delay between words while making sure it does not affect the performance much. The application ends the processing earlier than 1 sec if it sees some silence at the end of the word (THRESHOLD_LOW: increase to end faster) for certain amount of time (SILENCE_COUNTER_THRESHOL: reduce to end faster).  Please also note that the TFT display update time for each word increases the delay between words and you may disable that.
