### ISSUE TITLE
Using camera with pixel format RGB888 and USE_DMA results in incorrect image length

### ISSUE THREAD

**Issue by jmenges** [MaximIntegratedAI/MAX78000_SDK#66]
Hello,

when using the camera with the following parameters:

`ret = camera_setup(90, 90, PIXFORMAT_RGB888, FIFO_THREE_BYTE, USE_DMA, dma_channel);`

the resulting image length returned from

`camera_get_image(&frame_buffer, &imgLen, &w, &h);`

is 32400 bytes instead of the expected 24300 bytes.

The usage of dma temporarily increases the image size because bytes_per_pixel in Source/camera.c is set to 4.

snipped from function camera_setup()
```
if ((g_dma_mode == USE_DMA) || (g_dma_mode == STREAMING_DMA)) {
    bytes_per_pixel = 4;
}
```

In the function camera_get_image() the image is filtered when using dma  and RGB888, but the image size is not reduced back to the original size. To get around this issue, i have added another static int called g_real_img_size that is used as shown below. I was not able to come up with a cleaner solution.

`
void camera_get_image(uint8_t** img, uint32_t* imgLen, uint32_t* w, uint32_t* h)
{
    int n = 0, index;
    MXC_PCIF->int_fl |= MXC_PCIF->int_fl; // setup inf_fl register

    if (g_dma_mode == USE_DMA && g_pixel_format == PIXFORMAT_RGB888) {
        // Filter image data
        index = 4;

        for (n = 3; n < ((g_framesize_width) * (g_framesize_height) * 3); n++) {
            index++;

            if (index % 4 == 0) {
                index++;
            }

            rx_data[n] = rx_data[index - 1];
        }

        //reduce image to original length
        g_real_img_size = g_total_img_size / 4 * 3;
        *imgLen = g_real_img_size;
    } else {
        *imgLen = g_total_img_size;
    }

    *img    = (uint8_t*)rx_data;

    *w = g_framesize_width;
    *h = g_framesize_height;
}
`

BR

**Comment by vicloginov** [comment]
You are right. There is extra zero byte per pixel due to 32-bit aligned DMA transfer, but actual image size is 90x90x3.
We will do adjustments in future SDK release.
