### ISSUE TITLE
Debugger issue in Linux

### ISSUE THREAD

**Issue by KVital** [MaximIntegratedAI/MAX78000_SDK#68]
Hello
I'm using MAX78000FTHR board under Linux (Ubuntu 20.04). I try to load the compiled example code to the board, so for this I had tried to launch the openocd debugger, but I got an issue:

```
kvital@kvital:~$ openocd -f interface/cmsis-dap.cfg -f target/max78000.cfg -s/home/kvital/MaximSDK/Tools/OpenOCD/scripts
Open On-Chip Debugger 0.11.0+dev-g4f85f7914 (2021-12-16-13:50)
Licensed under GNU GPL v2
For bug reports, read
	http://openocd.org/doc/doxygen/bugs.html
DEPRECATED! use 'adapter driver' not 'interface'
Info : Listening on port 6666 for tcl connections
Info : Listening on port 4444 for telnet connections
Info : CMSIS-DAP: SWD  supported
Info : CMSIS-DAP: Atomic commands supported
Info : CMSIS-DAP: FW Version = 0254
Info : CMSIS-DAP: Serial# = 04440001f3fd8aac00000000000000000000000097969906
Info : CMSIS-DAP: Interface Initialised (SWD)
Info : SWCLK/TCK = 1 SWDIO/TMS = 1 TDI = 0 TDO = 0 nTRST = 0 nRESET = 1
Info : CMSIS-DAP: Interface ready
Info : clock speed 2000 kHz
Error: Error connecting DP: cannot read IDR
```

Can you tell me please how can I solve the problem?
The same code was successfully loaded on the board in Windows, so no problem with hardware.

Thank you in advance!

**Comment by KVital** [comment]
Issue was resolved with unlock procedure
https://github.com/MaximIntegratedAI/MaximAI_Documentation/blob/master/MAX78000_Feather/README.md

Thanks!

**Comment by rotx-maxim** [comment]
Thank you for letting us know, and glad to hear you resolved the issue.
(If you removed it, leaving the initial 2s delay in main.c may help in the future.)
