### ISSUE TITLE
Debugging multiple core

### ISSUE THREAD

**Issue by Gio200023** [MaximIntegratedAI/MAX78000_SDK#69]
Hi, I recently received the MAX78000FTHR board from my university and I'm having some trouble debugging the examples code. 
In this case I'm trying to run mnist-riscv example.
I begin to say that I use vscode, I also tried eclipse and from command line.  
When I flash the .elf or -combined.elf files into the board everything goes smooth, but when I try to debug it I'm able to debug only the arm core (I can make breakpoint and stop the work flow just in the main.c file --> the arm core main).
My .vscode configuration is pretty much equal to the one given with the examples.
Am I missing something? I mean, should I use an external debugger to debug riscv core?

Also I saw that in addition to the standard openocd executable there is also the openocd_riscv executable: should I use this one instead? Same thing for gdb command. 

This is my launch.json configuration:
![image](https://user-images.githubusercontent.com/75630696/167727143-4ea884a7-e718-4f27-9246-ee78f1aa2992.png)

I think is a Makefile problem, in particular the objcopy from the .elf to -combined.elf files.

I also tried to change some attribute in this gdb launch command but without good results. 
My goal is to debug both cores and be able to stop the workflow at breakpoints into the arm core and into the riscv core too.

Thank you

**Comment by Jake-Carter** [comment]
Hello,

Thank you for reaching out.  Dual-core debugging is an in-depth subject that I haven't had any time to document yet.  The mnist-riscv .vscode project settings should work without modification.

However, I noticed that RISC-V OpenOCD configuration file for the MAX78000 has seemingly disappeared from the SDK...  WIthout this file, the RISC-V launch profile will not work...

I am currently tracking down the file again.  Once I have it, I will write some official documentation on dual-core debugging.

I'll keep you updated!

**Comment by Gio200023** [comment]
Thank you very much,
I tried to find out the RISC-V configuration file without success. 
So I'm going to wait for your answer. 

Thank you again

**Comment by Jake-Carter** [comment]
I uncovered some issues with the RISC-V project that I will fix and merge into the SDK.  

For now, please use this project: [MAX78000-mnist-riscv-vscode.zip](https://github.com/MaximIntegratedAI/MAX78000_SDK/files/8691622/MAX78000-mnist-riscv-vscode.zip)
* The project is configured for the FTHR board.  Set `"board":"EvKit_V1"` in `.vscode/settings.json` if you're using the EVKIT.  
* The project is also configured for the [ARM-USB-OCD-H](https://www.olimex.com/Products/ARM/JTAG/ARM-USB-OCD/) debugger for the RISC-V port.  I'm assuming you have one of those available?

I've uploaded the missing RISC-V config file here ... [max78000_riscv_cfg.zip](https://github.com/MaximIntegratedAI/MAX78000_SDK/files/8691624/max78000_riscv_cfg.zip)
* Copy this file into the `Tools/OpenOCD/scripts/target` folder inside your SDK installation.  It should go next to the "max78000.cfg" and other OpenOCD config files.  Ex:  

    ![image](https://user-images.githubusercontent.com/38844790/168397647-862c1843-2f05-4c6f-9548-b7dbf6788128.png)

To debug the project:
1. Connect your Arm SWD and RISC-V debuggers

2. Make sure your Olimex debugger drivers are installed correctly.  I had to update mine using the zadig tool.  See [this](https://www.olimex.com/Products/ARM/JTAG/_resources/ARM-USB-OCD_and_OCD_H_manual.pdf) Olimex User Manual for more details.

3. Run the "Flash" task.

    ![image](https://user-images.githubusercontent.com/38844790/168398354-2ac2961b-6d45-4f84-8805-0ab5339a4b98.png)
    
4. Launch the debugger using the GDB (Arm M4) profile:

    ![image](https://user-images.githubusercontent.com/38844790/168398415-147a3a96-1a7d-4057-8a32-0dfaf2d378c1.png)
    
    ... which should hit the breakpoint in `main.c`...
    ![image](https://user-images.githubusercontent.com/38844790/168398503-0f2ae9c1-f535-4d41-aed9-9d9e19b16303.png)

5. Continue the debugger.  The code in `main.c` will boot up the RISC-V core and run it.  You can optionally set a breakpoint on `WakeISR` to see when the RISC-V core has signaled it's ready.

    ![image](https://user-images.githubusercontent.com/38844790/168398665-9486e1b6-73bd-481e-a4b5-15dd44c7d7b9.png)

6.  Now, launch another debugger window with the GDB (RISC-V) profile.
    
    ![image](https://user-images.githubusercontent.com/38844790/168398707-b6771bf3-b6bf-47a2-b963-b0b9fc003ca4.png)

    ... which should hit the breakpoint on main.  
    
    Notice the "Signal 0" exception below...  This is a known issue caused by a hardware bug on the RISC-V core that can be safely ignored.  Issuing a "reset halt" to the RISC-V core causes it to enter an illegal instruction handler.  I work around this by manually moving the program counter to the correct reset handler, but there is an internal status register that's proved difficult to clear.  The exception message is harmless, but annoying...  It will present itself every time the debugger is paused.
    
    ![image](https://user-images.githubusercontent.com/38844790/168399130-95fe7539-fb46-4c06-a268-6b720403b539.png)

7. From here, the debugger should be fully functional.  Ex, stepping through loading weights:

    ![image](https://user-images.githubusercontent.com/38844790/168399419-d0488a0e-2068-4cc7-9108-0a296fdc04b4.png)

Apologies for the annoying "Signal 0" false exception...  Currently investigating potential software workarounds.

Best Regards,
Jake

**Comment by Gio200023** [comment]
Unfortunately I do not have the olimex adapter. Instead I have the max32625pico adapter, loaded with max32625_daplink.bin file that according to the wiki it should boot the pico board in debug mode.
I tried with the pico adapter but it doesn't run. 

Due to the absent of the olimex adapter, using this command I had this output:
```
./openocd -s /home/gio/MaximSDK/Tools/OpenOCD -f interface/ftdi/olimex-arm-usb-ocd-h.cfg -f target/max78000_riscv.cfg
```
And I obtained:
```
Info : auto-selecting first available session transport "jtag". To override use 'transport select <transport>'.
Info : Listening on port 6666 for tcl connections
Info : Listening on port 4444 for telnet connections
Info : adv debug unit selected
Info : mohor tap selected
Error: no device found
Error: unable to open ftdi device with vid 15ba, pid 002b, description 'Olimex OpenOCD JTAG ARM-USB-OCD-H', serial '*' at bus location '*'
```

Then I tried with che cmsis-dap interface (if I'm not wrong it should be the right interface for pico):
```
./openocd -s /home/gio/MaximSDK/Tools/OpenOCD/scripts -f interface/cmsis-dap.cfg -f target/max78000_riscv.cfg
```
But it gave me this output:
```
Info : auto-selecting first available session transport "swd". To override use 'transport select <transport>'.
embedded:startup.tcl:128: Error: session transport is "swd" but your config requires JTAG
in procedure 'script'
```

So I added this to max78000-riscv.cfg
```
transport select JTAG
```
but:
```
Error: Debug adapter doesn't support 'JTAG' transport
target/max78000_riscv.cfg:6: Error:
in procedure 'script'
```

I'm going to ask my professor if I can have the olimex adapter to debug riscv.
In the meanwhile, is there any chance that the pico adapter is useful for my purpose?

Thank you again.

**Comment by Gio200023** [comment]
Thank you for the answer,
My professor wanted me to ask you if there are some alternatives.
The olimex arm-usb-ocd-h is out of stock right now and my university doesn't have one yet.

**Comment by Jake-Carter** [comment]
Please send me an email to jake.carter@analog.com with:
* Your full name
* Your phone number
* Your email address
* Your shipping address

and we'd be happy to send you an Olimex debugger and adapter.  We have some extras in stock :)

**Comment by Gio200023** [comment]
I sent an email. 
thank you again
