### ISSUE TITLE
When the input is 32 KHz, system doesn't working

### ISSUE THREAD

**Issue by Doruk-Dilmen** [MaximIntegratedAI/MAX78000_SDK#71]
I am working on kws20_demo example. I want to set input to 32 KHz. How can I give the 32 Khz microphone input to the system as 16kHz?

I tried that:
I changed CHUNK, TRANSPOSE_WIDTH and I2S_RX_BUFFER_SIZE
![image](https://user-images.githubusercontent.com/91119666/171572059-5022e2aa-931c-4578-b735-100f4735ef38.png)

Also, I changed the I2SInit() parameter to get 32 KHz audio input:
![tempsnip](https://user-images.githubusercontent.com/91119666/171572791-834213ec-a2fb-441b-91fa-d9c7d73af8e3.png)

The system works but does not fully understand what I am saying. For example I say "Six", system understands "Forward".

**Comment by aniktash** [comment]
The model is trained with 16khz audio samples, so it will not properly detect unless you retrain the model with 32khz samples.

**Comment by Doruk-Dilmen** [comment]
Yes I know that but I must set input to 32 KHz. Then, I think I can do downsampling. So the system will only get 32KHz audio but the model will do 16KHz audio samples.  Can you help me about this stuation

**Comment by aniktash** [comment]
You can
- set I2S_RX_BUFFER_SIZE to 128
-  set the clock divider to 2:   req.clkdiv      = 2;  //  (12.288M/2)  / ((2+1) *64) = 32khz
- Update the MicReadChunk to downsample after you read from i2s buffer, and before placing that in pBuff. For example
...
sample = HPF((int16_t)temp); // filter needs about 1K sample to converge
if (rx_size%2)
  continue;
...

**Comment by Doruk-Dilmen** [comment]
Yes, it works. Thank you so much.

Now I want to ask a different version of my questions. Ok, I am doing downsampling but how if I want to give 8Khz sample rate microphone input to the system as 16kHz?

**Comment by aniktash** [comment]
Correct.

**Comment by Doruk-Dilmen** [comment]
I tried, but it's not working. I didn't change CHUNK, TRANSPOSE_WIDTH and I2S_RX_BUFFER_SIZE
![image](https://user-images.githubusercontent.com/91119666/173520826-21a10fdb-1d60-4485-aa8d-06c0b5faa175.png)

I set req.clkdiv = 11 for 8KHz.
![soru1](https://user-images.githubusercontent.com/91119666/173521463-34c352f1-6cc3-49ee-8960-7c0db6102281.png)

I set chunkCount < 64. So, I could duplicate.
![soru2](https://user-images.githubusercontent.com/91119666/173522294-2043cb5e-14ee-4ed2-9f00-7da3894e9333.png)

Duplicate part;
![image](https://user-images.githubusercontent.com/91119666/173522600-c68c365c-9e59-433a-9356-7177d3d33363.png)

As a result, I can't solve the problem. Would you help me please?

**Comment by aniktash** [comment]
Here is the patch and works for 8khz: 
diff --git "a/Examples/MAX78000/CNN/kws20_demo/main.c" "b/Examples/MAX78000/CNN/kws20_demo/main.c"
index 93e0f6a8..f337cc9b 100644
--- "a/Examples/MAX78000/CNN/kws20_demo/main.c"
+++ "b/Examples/MAX78000/CNN/kws20_demo/main.c"
@@ -101,7 +101,7 @@
 #define CHUNK               128     // number of data points to read at a time and average for threshold, keep multiple of 128
 #define TRANSPOSE_WIDTH     128     // width of 2d data model to be used for transpose
 #define NUM_OUTPUTS         21      // number of classes
-#define I2S_RX_BUFFER_SIZE  64      // I2S buffer size
+**#define I2S_RX_BUFFER_SIZE  64/2 ///     // I2S buffer size**
 #define TFT_BUFF_SIZE       50      // TFT buffer size
 /*-----------------------------*/
 
@@ -698,7 +698,7 @@ void I2SInit()
     req.bitOrder    = MXC_I2S_MSB_FIRST;
     /* I2S clock = PT freq / (2*(req.clkdiv + 1)) */
     /* I2S sample rate = I2S clock/64 = 16kHz */
-    req.clkdiv      = 5;
+    **req.clkdiv      = 11;//5;**
     req.rawData     = NULL;
     req.txData      = NULL;
     req.rxData      = i2s_rx_buffer;
@@ -1046,11 +1046,13 @@ uint8_t MicReadChunk(uint8_t* pBuff, uint16_t* avg)
         }
 
         /* Convert to 8 bit unsigned */
-        pBuff[chunkCount] = (uint8_t)((sample) * SAMPLE_SCALE_FACTOR / 256);
+		pBuff[chunkCount] = (uint8_t)((sample) * SAMPLE_SCALE_FACTOR / 256);
+		**pBuff[chunkCount+1] = pBuff[chunkCount];**
 
         temp = (int8_t)pBuff[chunkCount];
 
-        chunkCount++;
**+        ///chunkCount++;
+		chunkCount+=2;**
 
         /* record max and min */
         if (temp > Max) {
