### ISSUE TITLE
MAX78000FTHR load fails with Apple M1 Pro

### ISSUE THREAD

**Issue by gorghino** [MaximIntegratedAI/MAX78000_SDK#72]
I'm using a MAX78000FTHR board under Apple M1 Pro (MacOS Monterey 12.2.1) and I'm trying to upload the HelloWorld example.

First of all, I uploaded its firmware with the max32625_max78000fthr_if_crc_v1.0.2 Debug Adapter Firmware.
I tried to build HelloWorld, setting FTHR_RevA in its Makefile. I was also using the latest Arm GNU Toolchain (gcc-arm-11.2-2022.02-darwin-x86_64-arm-none-eabi.pkg) 

There I started facing some compiler errors that I could fix setting -O0 in the MakeFile:

![photo_2022-06-16_11-29-41](https://user-images.githubusercontent.com/1898283/174408437-58e5cd3b-0a2f-410a-9655-8bc6ac682bf7.jpg)

With the latest GNU Toolchain I could create the elf file. I uploaded it following your guide. I got no errors neither on gdb nor openOCD but multiple mistmach with `compare-sections`. Restarting the board, booted the default program instead of running the HelloWorld.

Eventually, I tried the toolchain you suggested in the guide (gcc-arm-none-eabi-9-2019-q4-major) but that fails during load procedure:

![image](https://user-images.githubusercontent.com/1898283/174408940-9bb5c337-8733-4116-9af6-90163a4793ef.png)

Any ideas? Thank you!

**Comment by aniktash** [comment]
Here is the instruction to get the SDK installed properly on M1:
### INSTALLING SDK ON MAC M1

1- Get the package : (https://www.maximintegrated.com/en/design/software-description.html/swpart=SFW0018610A)

On MacOS the installer is distributed inside of a .dmg disk image file. Double click the downloaded file to mount it. Afterward, the installer executable will be made available inside the mounted drive. ( you may need to change the security to allow)

2- Install Homebrew (*running terminal in Rosetta for M1*):

- open a terminal and update Rosetta:   softwareupdate --install-rosetta --agree-to-license
- close terminal
- run a new terminal in Rosetta:
  - Go to Finder > Applications     and find your Terminal
  - Right-Click the App and  Duplicate it and rename it "Terminal i386"
  - Right-Click "Terminal i386" > Get Info > Enable Open using Rosetta
  - Click to Open the Terminal i386, type `arch` to verify it says `i386` now.
- Install brew ((https://brew.sh/)](https://brew.sh/)):
  - sudo /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

3- Install openOCD dependencies:

- brew install libusb-compat libftdi hidapi libusb



****Eclipse:***

- In MaximSDK, run:  ./run_eclipse.sh

- import project

- If building for feather: project>properties>C/C++ Build/Environment/Board, change Value from EvKit_V1 to FTHR_RevA

- If feather has a TFT, open Makefile and enable:

  ```
  ifeq "$(BOARD)" "FTHR_RevA"
  PROJ_CFLAGS+=-DTFT_ENABLE
  endif
  ```

- build and run/debug

  

**Terminal:**

- In MaximSDK, run: ./setenv.sh
- cd to Examples/MAX78000/Hello_world
- If you are building for feather, change $(BOARD) in Makefile. Also, enable TFT if needed:

  ```
  # Specify the board used
  ifeq "$(BOARD)" ""
  #BOARD=EvKit_V1
  BOARD=FTHR_RevA
  endif

  ...

  
  ifeq "$(BOARD)" "FTHR_RevA"
  # Only enable if 2.4" TFT is connected to Feather
  PROJ_CFLAGS+=-DTFT_ENABLE
  endif
  ```

- make -r to build
- flash and run:
  - openocd -s ~/MaximSDK/Tools/OpenOCD/scripts -f interface/cmsis-dap.cfg -f target/max78000.cfg  -c "program build/MAX78000.elf reset exit"
