### ISSUE TITLE
Inference time for cats dogs is significantly different from what is demonstrated

### ISSUE THREAD

**Issue by hyunjongL** [MaximIntegratedAI/MAX78000_SDK#74]
Hi, 
I ran the examples on the maxrefdes178's max78000 and on Featherboard's max 78000 and the inference time of cats-dogs and faceid are significantly different from what I expected. Mnist and cifar-100 had very similar inference time to that described. 
I am curious why there is a large difference for these models. 

cats-dogs: 
>Waiting...
*** CNN Inference Test ***
*** PASS ***
Approximate data loading and inference time: 12481 us
Classification results:
[  37303] -> Class 0: 97.0%
[ -37407] -> Class 1: 3.0%

https://github.com/MaximIntegratedAI/MAX78000_SDK/tree/master/Examples/MAX78000/CNN/cats-dogs (2549 us)

Also with faceid, I expected inference time of about 1.4ms, however it took 14ms. 
> Waiting...
*** CNN Inference Test ***
*** PASS ***
Approximate data loading and inference time: 14001 us

https://github.com/MaximIntegratedAI/MAX78000_SDK/tree/master/Examples/MAX78000/CNN/faceid (1882 us)

**Comment by hyunjongL** [comment]
I guess the difference comes from time to not only run CNN but to stream the data on the go.
In my eyes, the two examples streamed (relatively) large data which takes more time than processing a still data.

**Comment by rotx-maxim** [comment]
Correct, the time shown is the time to load the data and do the inference. This is needed for those examples that use streaming mode. When the data can be fully preloaded, then it's possible to compute only the inference time.
When you look at the generated code, you may find ways to speed up the data loading time. For example, by default the code uses a safety checks to avoid overrunning input FIFOs. When you know that your data source is slow enough, these safety checks can be removed, which drastically speeds up the loading time (there are comments in the code indicating where this can be done).
