### ISSUE TITLE
Microphone Problem

### ISSUE THREAD

**Issue by jim-carter-12** [MaximIntegratedAI/MAX78000_SDK#80]
Hi everyone,

I wanna use earphone for word detection. Can you share example code if you have?

**Comment by jessexm** [comment]
To create a modified version of the kws20_demo using a microphone connected to the CODEC line-in as data source you will need to:
- Copy the unmodified CNN\kws20_demo directory to a new project directory
- Extract the MAX9867 driver files in the attached archive into the new project directory
- Within main.c add includes for i2c.h and max9867.h
- Within main.c replace call to Microphone_Power with max9867_init.  The CODEC is connected to I2C instance MXC_I2C1 and the master clock frequency is 12.288MHz

[max9867_files.zip](https://github.com/MaximIntegratedAI/MAX78000_SDK/files/9472604/max9867_files.zip)

**Comment by jim-carter-12** [comment]
Hi,

I did what you said. I added i2c.h and max9867.h to main.c. 

I replaced call to Microphone_Power with max9867_init like below
> 	    Microphone_Power(POWER_OFF);
>	    mxc_i2c_regs_t microphone;
>	    max9867_init(&microphone,12.288);

At the moment, I can't take any inputs

**Comment by jim-carter-12** [comment]
Hi,
I configured your shared file as below. But it didn't not worked. 

I replaced call to Microphone_Power with max9867_init like below

>Microphone_Power(0);
> max9867_init(MXC_I2C1, MHZ(12.288));

                

[max9867.zip](https://github.com/MaximIntegratedAI/MAX78000_SDK/files/9582050/max9867.zip)

**Comment by jessexm** [comment]
Does the project build successfully or is it that no input is being detected?

If the project does build successfully then remove the call to Microphone_Power(0), rebuild the project, load the just built project and power cycle the board.

The 3.5mm jack J5 is the line-in to the CODEC and as such requires a line-in compatible microphone signal. A line-in microphone will be self-powered. A non line-in microphone may expect the be powered via a bias circuit in the connected system and the signal level is much smaller than a line-in microphone.  There are no connections to the microphone inputs of the CODEC installed on the MAX78000FTHR.
