### ISSUE TITLE
Warning in RTC module causes compilation error in https://github.com/MaximIntegratedAI/refdes

### ISSUE THREAD

**Issue by vicloginov** [MaximIntegratedAI/MAX78000_SDK#81]
![refdes_error](https://user-images.githubusercontent.com/65688219/188981966-26eb94b6-e09e-4ebc-a86c-e0fb84673f4d.png)

**Comment by vicloginov** [comment]
I will temporary disable "Werror" until it's fixed in MSDK

**Comment by Jake-Carter** [comment]
Fixed in https://github.com/Analog-Devices-MSDK/msdk/pull/216/commits/9cbc3c42ff643d37d77d23437bf6333259c6f0c2 merged in https://github.com/Analog-Devices-MSDK/msdk/pull/216 to be captured in the release candidate this week
