### ISSUE TITLE
C++ support

### ISSUE THREAD

**Issue by ramkumarkoppu** [MaximIntegratedAI/MAX78000_SDK#82]
I can see that SDK for windows supports C but couldn't find much information on building C++ application using this SDK. is C++ application possible with SDK for windows/Linux?

**Comment by Jake-Carter** [comment]
Hi @ramkumarkoppu,

The SDK does not support C++ yet.  We need to make the C code in our include-safe for C++, and our build system needs some additional work to enable it beyond anything trivial.

We have been getting some requests for this recently, so it is on our agenda to consider tackling this in the future.  I'd be curious as to what your use-case is.  Any particular C++ libraries/features that you're interested in?  Porting an existing application?
