### ISSUE TITLE
CSI RAW10/8 conversion to RGB888 shows artifacts

### ISSUE THREAD

**Issue by isztldav** [MaximIntegratedAI/MAX78000_SDK#84]
Hello,
I just ran your CSI2 example (https://github.com/MaximIntegratedAI/MAX78000_SDK/tree/master/Examples/MAX78002/CSI2) without any change.
It seems like that the debayering process leads to artifacts.
In the picture below you can observe the same imagine twice. In the left case it was debayered and then transferred to the computer, while on the right side the image was dumped before the debayering (via jtag and its represented before debayering and therefore the colors are not accurate)

![left debayered, right not debayered](https://user-images.githubusercontent.com/3083964/197349021-2c8be424-1e0a-42d6-9a22-3a3b02800d85.png)

it can be noticed that the noise was introduced during the debayering process. I also tried a different image size and I ended up with similar results (image saved after the debayering):
![image-out](https://user-images.githubusercontent.com/3083964/197349219-cc8d7a0a-e548-4662-91c4-2c9f818725d3.png)

The noise changes but it is still present.

Any suggestion?
Thank you

**Comment by isztldav** [comment]
Thank you @Jake-Carter . Please also consider my pull request https://github.com/MaximIntegratedAI/MAX78000_SDK/pull/83 (it fixes that the first time the DMA is not waited).
Also if you need more info from my side let me know

**Comment by Jake-Carter** [comment]
Thanks for reporting this @isztldav, we have been able to replicate the issue.  Our development for the SDK has migrated to https://github.com/Analog-Devices-MSDK/msdk, so we will migrate your PR and this ticket over to that repo.

![Image](https://user-images.githubusercontent.com/38844790/198755924-e153d86d-5efd-4deb-bd81-8693789fa6d0.png)

The debayering process for the CSI2 interface is done in hardware, so we are investigating our drivers further

**Comment by Jake-Carter** [comment]
Hi @isztldav, just want to send you a quick update.  This appears to have been the result of some deep-rooted memory contention issues in the CSI2 peripheral hardware.  However, I've been able to resolve them and capture a clean QVGA image without artifacts by separating the RAM instances used by the debayering hardware and the VFIFO -> DMA chain.

![Image](https://user-images.githubusercontent.com/38844790/201446003-f47c7304-5eb3-49f0-a71c-b2fd06e8d376.png)

We appreciate your patience and apologize for the delay.  It has taken some significant troubleshooting and re-working of our example.

I will be completing the work next week and submitting it for review and release.

**Comment by isztldav** [comment]
Hello @Jake-Carter, thank you very much for the update. Your work is really appreciated and your fixed example will be very useful.

**Comment by Jake-Carter** [comment]
@isztldav The fix has been merged into our https://github.com/Analog-Devices-MSDK/msdk repo.  We will be migrating from the MAX78000_SDK -> MSDK soon, so you can retrieve the MSDK now if you'd like to develop off the latest examples and drivers.

You can set up your ai8x-synthesis repo to reference the full MSDK with the set of commands below.  Alternatively, you can sync with my fork:  https://github.com/Jake-Carter/ai8x-synthesis.

Deinit and remove the old submodule (**will delete any tracked contents in ai8x-synthesis/sdk**)
```shell
git submodule deinit --force -- sdk
```
```shell
rm -rf .git/modules/sdk
```
```shell
git rm -rf sdk
```

Re-add the submodule using the MSDK's URL (I used the URL, see ["Cloning the repo"](https://github.com/Analog-Devices-MSDK/msdk#cloning-the-github-repo))...
```shell
git submodule add git@github.com:Analog-Devices-MSDK/msdk.git sdk
```

The MSDK should be compatible with the same [manual setup procedure](https://github.com/MaximIntegratedAI/ai8x-synthesis#method-2-manual-installation) in the AI8x documentation if you've already followed it.  Alternatively, you can set up symbolic links for the repo following ["Developing from the Repo"](https://github.com/Analog-Devices-MSDK/msdk#developing-from-the-repo)

The [fixed CSI2 example](https://github.com/Analog-Devices-MSDK/msdk/tree/main/Examples/MAX78002/CSI2) has an improved console (same as ImgCapture but with a limited command set) and is working for QVGA 320x240.  We are still working on strategies for VGA 640x480, which are beyond the built-in SRAM limits of the device.
